export EXEC_PREFIX=_build/install/default/bin
export TRACKER=tracker
export RPC_SERVER=rpc_server
export RPC_CLIENT=rpc_client
export CLIENT=btclient
export SCRIPTS_PREFIX=scripts
export OCAML_TORRENT=1
export TEST_PATH_PREFIX=download
export TORRENT=multifiles_localhost_6969.torrent 
export BITSET=79cbdfd46e222f3c515df5db23d64d43bea345b3.bitset
export TORRENT_DIR=tests/torrents
export FILES=tests/multifiles
export NUM_PIECES=66
export NUM_CLIENTS=10
export BASE_PORT=6000
export BASE_RPC_PORT=7000
export VERBOSE="-v 2"
