export EXEC_PREFIX=_build/install/default/bin
export TRACKER=bt_tracker
export RPC_SERVER=sawadee_rpc
export TEST_TORRENT=test_simple_torrent
export TEST_DHT=test_dht
export CLIENT=sawadee
export SCRIPTS_PREFIX=scripts
export OCAML_TORRENT=1
export TEST_PATH_PREFIX=download
export TORRENT=multifiles_localhost_6969.torrent 
export BITSET=e816b060122c95fa171e41227b12b4a8f30c4e20.bitset
export TORRENT_DIR=tests/torrents
export DHT_LOCAL=tests/routing.local
export DHT=routing
export FILES=tests/multifiles
export FILE_MAGNET=tests/singlefile/11318.jpg 
export NUM_PIECES=66
export NUM_CLIENTS=10
export BASE_PORT=6000
export BASE_RPC_PORT=7000
export VERBOSE="-v 2"
export TIME_TO_WAIT=12
export TIME_TO_WAIT2=40

