export EXEC_PREFIX=scripts
export OCAML_TORRENT=1
export TEST_PATH_PREFIX=download
export TORRENT=multifiles_localhost_6969.torrent 
export TORRENT_DIR=tests/torrents
export FILES=tests/multifiles
export BITSET=165
export NUM_CLIENTS=20
export BASE_PORT=6000
export VERBOSE="-v 2"
